[linters]
enable-all = true
disable = [
  "wsl",
  "testpackage",
  "varnamelen",
  "depguard",
  "revive",
  "stylecheck",
  "exhaustruct",
  "wrapcheck",
  "noctx",
  "exportloopref",
  "gochecknoglobals", # Too strict
]

[issues]
exclude-dirs = ["tests/"]
