listen = "localhost:3000"

[log]
level = "DEBUG"
file = "log"

[redis]
enabled = true
address = "localhost:6379"
db = 0
user = "test"
password = "Password123"

[alerting]
interval = 1

[[probe]]
name = "example" # Unique name for probe
description = "Check https://example.org website"
module = "http"
[probe.http]
target = "https://example.org"
valid = [200, 404]
[probe.webhooks]
enabled = true
username = "Status alert"
url = "https://discord.com/api/webhooks/28357/verysecuretoken"
