name: Build

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/r4iponce/status:latest
          file: deployment/docker/Dockerfile
  build:
    runs-on: ubuntu-latest
    name: Build status
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: make build
      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: |
            status
            build/
