name: Test Go

on:
  pull_request:
    paths:
      - 'internal/**'
      - 'test/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - main
    paths:
      - 'internal/**'
      - 'test/**'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22', '1.23' ]
    name: test status with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Setup redis
        run: sudo apt-get update && sudo apt-get install -y redis-server
      - run: go test ./...
